name: Initiate Repo

on:
  create:
  workflow_dispatch:

permissions:
  contents: write
  repository-projects: write
  
# see https://jmh.me/blog/build-deploy-php-application-with-github-actions
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_DEV: 1
    steps:
      - name: Set publishing branch to gh-pages
        run: |
          gh api --method PUT -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$OWNER/$REPO/pages \-f "source[branch]=gh-pages" -f "source[path]=/"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }} 

